# storage for move functions used for testing.

def walking_to_water_test(Game):
    Game.gameMove('s')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('s')
    Game.gameMove('s')

def walking_to_fire_test(Game):
    Game.gameMove('s')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')    
    Game.gameMove('d')
    Game.gameMove('e')
    Game.gameMove('s')
    Game.gameMove('s')
    Game.gameMove('a')
    Game.gameMove('s')
    Game.gameMove('s') 
    Game.gameMove('d')
    Game.gameMove('s')
    Game.gameMove('d')
    Game.gameMove('d')

def putting_out_fire_test(Game):
    Game.gameMove('w')
    Game.gameMove('w')    
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('e')
    Game.gameMove('s')
    Game.gameMove('s')
    Game.gameMove('a') 
    Game.gameMove('s')
    Game.gameMove('s')
    Game.gameMove('d')
    Game.gameMove('s')
    Game.gameMove('d')
    Game.gameMove('d')    

def walking_to_teleporter_test(Game):
    Game.gameMove('s')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')    
    Game.gameMove('d')

def walking_off_grid(Game):
    Game.gameMove('s')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')    
    Game.gameMove('d')
    Game.gameMove('e')
    Game.gameMove('s')
    Game.gameMove('s')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('e')
    Game.gameMove('d')    
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
    Game.gameMove('d')
